//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusFleetManagerSystem.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusFleetManagerSystemDBEntities : DbContext
    {
        private static BusFleetManagerSystemDBEntities _context;
        public BusFleetManagerSystemDBEntities()
            : base("name=BusFleetManagerSystemDBEntities")
        {
        }

        public static BusFleetManagerSystemDBEntities GetContext()
        {
            if (_context == null)
                _context = new BusFleetManagerSystemDBEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<BusRoute> BusRoutes { get; set; }
        public virtual DbSet<BusType> BusTypes { get; set; }
        public virtual DbSet<DeparturePoint> DeparturePoints { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
    }
}
